name: ScienceGateway
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - absl-py
  - amqp
  - astunparse
  - async-timeout
  - billiard
  - cachetools
  - celery
  - certifi
  - charset-normalizer
  - click
  - click-didyoumean
  - click-plugins
  - click-repl
  - config
  - dnspython
  - environs
  - eventlet
  - filelock
  - Flask
  - Flask-WTF
  - flatbuffers
  - gast
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - greenlet
  - h5py
  - idna
  - itsdangerous
  - jax
  - Jinja2
  - keras
  - kombu
  - libclang
  - Markdown
  - MarkupSafe
  - marshmallow
  - mpmath
  - networkx
  - numpy
  - oauthlib
  - packaging
  - Pillow
  - prompt-toolkit
  - pyasn1
  - pyasn1-modules
  - python-dotenv
  - pytz
  - PyYAML
  - regex
  - requests
  - requests-oauthlib
  - rsa
  - scipy
  - six
  - sympy
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-estimator
  - termcolor
  - tokenizers
  - tqdm
  - transformers
  - typing_extensions
  - urllib3
  - vine
  - wcwidth
  - Werkzeug
  - wrapt
  - WTForms
